#pragma once
#include "input/day1.h"
#include "input/day2.h"
#include "input/day3.h"
#include "input/day4.h"
#include "input/day5.h"
#include "input/day6.h"
#include "input/day7.h"
#include "input/day8.h"
